### ISSUE TITLE
Can't see any data inside Kibana.

### ISSUE THREAD

**Issue by dimpol** [dactivllc/osquery-in-a-box#1]
Hi there,
Thank you for making the setup easier with this GIT.

I followed your detailed guidelines to the letter and i can see all hosts online inside fleet.
I can't see any data inside kibana though (i run 2-3 queries across the whole fleet successfully). 
"Check for new data" always results in nothing.

Should i configure something inside the settings on Kibana?
Since i don't see any data, i can't configure the index name...

Thanks in advance for the help...

**Comment by zwass** [comment]
Hi @dimpol, please take a look at https://github.com/kolide/fleet/blob/master/docs/infrastructure/faq.md#where-are-my-query-results.

I'm guessing the issue is that you are running live queries but you have not scheduled any queries. Only the scheduled query results will make it to ELK.

**Comment by dimpol** [comment]
@zwass 
You are absolutely right.
Sorry for the stupid question...

Thanks for taking the time to look into this..
